Added a timestamp to the root node of the json result
sindresorhus/speed-test pull request #67
Opened 2020-10-27 07:20 UTC by gnud

- Updated readme to include batch example
- The timestamp is only included via json argument and verbose all together, providing ability to monitor the results via some tool

2020-10-28 11:29 UTC, sindresorhus requested changes

2020-10-28 11:29 UTC, sindresorhus commented on readme.md
> +## Batch monitoring
```suggestion
## Tips

### Batch monitoring
```

2020-10-28 11:29 UTC, sindresorhus commented on readme.md
> +while true; do sleep 30; node cli.js -v -j; done >> ~/net.log
Use the long flags.

2020-10-28 11:29 UTC, sindresorhus commented
Can you mention in the readme that the JSON output also includes a timestamp?

2020-10-28 11:55 UTC, gnud reviewed
Added suggested changes, please confirm if they were applied.

2020-10-28 21:53 UTC, sindresorhus commented
> please confirm if they were applied.

I don't understand what this means. You can confirm yourself.

2020-10-28 21:54 UTC, sindresorhus commented
You still need to do https://github.com/sindresorhus/speed-test/pull/67#issuecomment-717872597

2020-10-29 11:37 UTC, gnud reviewed
All done :).

2020-11-02 01:07 UTC, sindresorhus commented on readme.md
> +**Note**: using the **"--verbose"** and **"--json"** will include a timestamp **e.g**: "1603971242534" property generated now in form of a timestamp, good for recording the metrics in some monitoring
This should be documented generally. It's not specific to "batch monitoring".

2021-03-07 10:58 UTC, sindresorhus commented
@gnud Friendly bump :)

2021-06-03 19:31 UTC, sindresorhus commented
Closing for lack of activity.

2021-06-03 19:31 UTC, closed without merging